//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABLANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public Nullable<decimal> IdCustommer { get; set; }
        public Nullable<decimal> IdProductDetail { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal SumPrice { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
