//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABLANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryReceipt()
        {
            this.InventoryReceiptDetails = new HashSet<InventoryReceiptDetail>();
        }
    
        public decimal ID { get; set; }
        public string PO_No { get; set; }
        public Nullable<decimal> EmployeeID { get; set; }
        public System.DateTime PODate { get; set; }
        public string Note { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryReceiptDetail> InventoryReceiptDetails { get; set; }
    }
}
