//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABLANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReceiptDetail
    {
        public decimal ReceiptID { get; set; }
        public decimal ProductID { get; set; }
        public double Quantity { get; set; }
        public double Prices { get; set; }
    
        public virtual InventoryReceipt InventoryReceipt { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
