//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABLANCE.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.PromotionDetails = new HashSet<PromotionDetail>();
        }
    
        public decimal ID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }

        public Nullable<System.DateTime> StartTime { get; set; }

        public System.DateTime EndTime { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> CategoriesPromotionID { get; set; }
    
        public virtual CategoriesPromotion CategoriesPromotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionDetail> PromotionDetails { get; set; }
    }
}
