//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABLANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionDetail
    {
        public decimal ProductDetailsID { get; set; }
        public decimal PromotionID { get; set; }
        public double Discount { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
